package com.example.kahaapplication;

public enum Keys {
    COLLECTION_USERS,
    COLLECTIONS_SPACES,
    SPACES,

    //SPACE DETAILS
    KEY_SPACE_THUMBNAIL,
    KEY_SPACE_LENGTH,
    KEY_SPACE_WIDTH,
    KEY_SPACE_HEIGHT,
    KEY_SPACE_PRICE,
    KEY_SPACE_HOST,
    KEY_SPACE_TYPE,
    KEY_SPACE_LOCATION,
    KEY_SPACE_DESCRIPTION,
    KEY_SPACE_HOST_ID,
    KEY_SPACE_UPLOAD_ID
}
