package com.example.kahaapplication;

public enum Keys {
    COLLECTIONS_PROFILES,
    COLLECTIONS_SPACES,
    COLLECTIONS_RESERVEES,
    SPACES,

    //SPACE DETAILS
    KEY_SPACE_THUMBNAIL,
    KEY_SPACE_LENGTH,
    KEY_SPACE_WIDTH,
    KEY_SPACE_HEIGHT,
    KEY_SPACE_PRICE,
    KEY_SPACE_HOST,
    KEY_SPACE_TYPE,
    KEY_SPACE_LOCATION,
    KEY_SPACE_DESCRIPTION,
    KEY_SPACE_HOST_ID,
    KEY_SPACE_UPLOAD_ID,
    KEY_LAT,
    KEY_LNG,
    KEY_SPACE_VIEW_FROM_PROFILE,

    //FINDER DETAILS
    KEY_FINDER_FIRST,
    KEY_FINDER_LAST,
    KEY_FINDER_BIRTH,
    KEY_FINDER_DESC,
    KEY_FINDER_EMAIL,
    KEY_FINDER_PHONE,
    KEY_BOOK_MARKS,
    KEY_SPACE_CONTACT_NUMBER,

    //SESSION DETAILS
    KEY_USER_ID
}
